name: Test on Python 3.10-3.13

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint pytest poetry
          pip install .

      - name: Lint with Pylint and Annotate
        if: matrix.python-version == '3.10'
        uses: reviewdog/action-pylint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check  # Use GitHub Checks API for annotations
          level: warning          # Set the annotation level
          pylint_flags: ''        # Add any Pylint flags if needed
          pylint_targets: './'    # Target directory or files to lint

      - name: Test with pytest
        run: pytest
